version: "3.2"

services:

  backend:
    build: .
    volumes:
      - testDrive:/backendVol
    networks:
      - forRestCalls
    ports:
      - 5006:5006

  frontend:
    build: ./box-moving-frontend
    networks:
      - forRestCalls
    ports:
      - 5005:5005

  db:
    image: mysql:8
    volumes:
      - data:/var/lib/mysql
    networks:
      - database

networks:
  forRestCalls:
  database:

volumes:
  testDrive:
  data:
