version: "3.2"

services:

  backend:
    build: .
    volumes:
      - variousShit:/backendVol
    networks:
      - forRestCalls
    ports:
      - 8080:8080

  frontend:
    build: ./box-moving-frontend
    networks:
      - forRestCalls
    ports:
      - 8081:8081

networks:
  forRestCalls:

volumes:
  variousShit:
