version: "3.2"

services:

  backend:
    build: .
    volumes:
      - variousShit:/backendVol
    networks:
      - forRestCalls
    ports:
      - 5000:5000

  frontend:
    build: ./box-moving-frontend
    networks:
      - forRestCalls
    ports:
      - 5005:5005

networks:
  forRestCalls:

volumes:
  variousShit:
